name: scarbous/node-runner
branding:
  icon: package
  color: orange
description: It will install and run your npm script
inputs:
  dir:
    description: base dir of
    default: "/"
  task:
    description: The name of the npm script to run
    default: "build"
runs:
  using: 'docker'
  env:
    DIR: "/github/workspace/${{ inputs.dir }}"
    TASK: ${{ inputs.task }}
  image: "Dockerfile"
