name: Docker Image CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "entrypoint.sh"
      - "Dockerfile"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { NODE_VERSION: 14 }
          - { NODE_VERSION: 16 }
          - { NODE_VERSION: 18 }
          - { NODE_VERSION: 19 }
    env:
      DOCKER_IMAGE: scarbous/node-runner/${{ matrix.env.NODE_VERSION }}
      GHCR_DOCKER_IMAGE: ghcr.io/scarbous/node-runner/${{ matrix.env.NODE_VERSION }}
      BuildArgs: NODE_VERSION=${{ matrix.env.NODE_VERSION }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.GITHUB_REF_NAME == 'main' && github.GITHUB_REF_TYPE == 'branch' }}
          builder: ${{ steps.buildx.outputs.name }}
          build-args: ${{ env.BuildArgs }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.GHCR_DOCKER_IMAGE }},${{ env.DOCKER_IMAGE }}
